name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install node 12.18.1
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.1'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout project repository
        uses: actions/checkout@v2

      - name: Setup CDK, deploy project
        run: |
          npm install
          npm run cdk bootstrap
          npm run cdk synth
          npm run cdk deploy -- --require-approval=never
